#!/bin/sh
#
# Xmpp-Socket   /etc/init.d/ initscript for Xmpp-Socket
#               $Id: xmpp-socket.init,v 1.6 2004/09/30 01:04:04 hmh Exp $
#
#               Copyright (c) 2014-2014 Simone Vellei <henomis@gmail.com>
#
#               Distributed under the GPL version 2
#

### BEGIN INIT INFO
# Provides: xmpp-socket
# Required-Start: $remote_fs
# Required-Stop: $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop xmpp-socket
# Description:  Xmpp-Socket is a very high quality software-only MIDI sequencer
#        and MOD player.
### END INIT INFO

. /lib/lsb/init-functions

NAME="xmpp-socket"
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/${NAME}
DESC="Xmpp-Socket service"
PIDFILE=/var/run/${NAME}.pid

set -e

test -x ${DAEMON} || exit 0

[ -r /etc/default/xmpp-socket ] && . /etc/default/xmpp-socket

#[ -z "$SERVER_USER" ] && SERVER_USER=xmpp-socket
#[ -z "$SERVER_GROUP" ] && SERVER_GROUP=xmpp-socket

#if ! getent passwd | grep -q "^${SERVER_USER}:"; then
#log_daemon_msg "Server user does not exist. Aborting"
#log_end_msg 0
#exit 1
#fi
#if ! getent group | grep -q "^${SERVER_GROUP}:" ; then
#log_daemon_msg "Server group does not exist. Aborting"
#log_end_msg =
#exit 1
#fi

PARAMS=""


START="--start --quiet --exec ${DAEMON} --pidfile ${PIDFILE} -- ${PARAMS}"
#START="--start --chuid ${SERVER_USER} --quiet --exec ${DAEMON} --pidfile ${PIDFILE} -- ${PARAMS}"

case "$1" in
  start)
	#log_daemon_msg "Starting" "${NAME}"
	log_begin_msg "Starting $DESC..."
    #mkdir -p /var/run/xmpp-socket
    #chown xmpp-socket /var/run/xmpp-socket
	if start-stop-daemon ${START} < /dev/null >/dev/null 2>&1; then
		log_end_msg 0
	else
		log_end_msg 1
		exit 1
	fi
	;;
  stop)
	log_begin_msg "Stopping $DESC..."
	if start-stop-daemon --stop --oknodo --pidfile ${PIDFILE} \
          --name ${NAME} --retry 10 ; then
		log_end_msg 0
	else
		log_end_msg 1
		exit 1
	fi
	;;
  restart|force-reload)
  	$0 stop
	exec $0 start
  	;;
  status)
	status_of_proc $DAEMON $NAME
	;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
    exit 1
esac
 
exit 0
